id: P794CD848
initial_creation_type: input
source_metadata:
  title: Yamāntaka Series
  language: it
  description: 'Texts related to Yamāntaka (gshin rje gshed), the wrathful form of
    Mañjuśrī:'
  volume:
    2979e6fa9a6748bf8c5e9cc364170858:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Sādhanas
    e1c1f5462501453c81527ce359578b27:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Sādhanas
created_at: '2022-03-01T06:35:53.230796'
last_modified_at: '2022-03-01T06:35:53.230798'
